---
version: "3"

services:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/Watch:/srv/media
    networks:
      - default
    ports:
      #- 8989:8989
      - 8989
    mem_limit: 4096m
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/Watch:/srv/media
    ports:
      - 7878
    mem_limit: 4096m
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/jackettconfig:/config
      - /volume1/Matrix/Downloads:/downloads
    networks:
      - default
    ports:
      - 9117
    mem_limit: 4096m
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TEST=ok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - default
    ports:
      - 443:443
    restart: unless-stopped

networks:
  default:
    name: fileshare-network