---
version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
    volumes:
      - /srv/other/docker/fileshare/config-sonarr:/config
      - /srv/media:/srv/media
    ports:
      - 8989:8989
    mem_limit: 4096m
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
    volumes:
      - /srv/other/docker/fileshare/config-radarr:/config
      - /srv/media:/srv/media
    ports:
      - 7878:7878
    mem_limit: 4096m
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=121
      - TZ=America/Phoenix
        #- RUN_OPTS=<run options here> #optional
    volumes:
      - /srv/other/docker/fileshare/config-jackett:/config
      - /srv/other/docker/downloads:/downloads
    ports:
      - 9117:9117
    mem_limit: 4096m
    restart: unless-stopped
  web_proxy:
    image: nginx:latest
    container_name: nginx
    environment:
      - TEST=ok
    volumes:
      - ./nginx.conf:/etc/nginx/templates
    ports:
      - 443:443
    restart: unless-stopped


