#! 
#! cd /volume1/docker/mediagrab;sudo -u root docker-compose -f docker-compose.yml up -d  --remove-orphans
---
version: "3"
services:

  sonarr:
    container_name: sonarr
    # image: linuxserver/sonarr:latest
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - ./sonarr/config/:/config
      # - /volume1/Watch/_file/:/media/file
      - /volume1/Watch/:/media
      # - /volume1/Watch/TV/:/TV   
    networks:
      - default
    ports:
      - 8989:8989
      #- 8989 assigns to random port
    mem_limit: 4096m
    restart: unless-stopped

  radarr:
    container_name: radarr
    # image: linuxserver/radarr:latest
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - ./radarr/config/:/config
      - /volume1/Watch/:/media
      # - /volume1/Watch/Movies/:/Movies
    ports:
      - 7878:7878
    mem_limit: 4096m
    restart: unless-stopped

  jackett:
    container_name: jackett
    # image: linuxserver/jackett:latest
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
    volumes:
      - ./jackett/config/:/config
      - /volume1/Watch/:/media
      # - /volume1/Watch/_blackhole:/media/blackhole
    networks:
      - default
    ports:
      - 9117:9117
    mem_limit: 4096m
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - TEST=ok
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - default
    ports:
      - 8443:443
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8888
    volumes:
      - ./qbittorrent/config:/config
      - /volume1/Watch/:/media
      # - /volume1/Watch/TV/:/media/TV
      # - /volume1/Watch/Movies/:/media/Movies
      - /volume1/Matrix/Dropbox/Downloads/:/watch
    ports:
      - 8888:8888
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  unpackerr:
    container_name: unpackerr
    image: cr.hotio.dev/hotio/unpackerr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - UMASK=002
    volumes:
      - /volume1/docker/mediagrab/unpackerr/:/config
      - /volume1/Watch/_new/:/data
    # network_mode: synobridge
    restart: unless-stopped
  # qbittorrent-setup:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   command: sh -c "/config.sh"

    # command: sh config.sh
    # command: sh -c "/config.sh"
    # command: sh -c "/config.sh && exec myexecutable"
    # volumes: 
    #   - ./init.sh:/init.sh
    # entrypoint: sh -c "/config.sh"
    # depends_on:
    #   - qbittorrent
    # restart: "no"
    # entrypoint: [ "bash", "-c", "sleep 10 && mongo --host mongo:27017 --eval 'rs.initiate()'"] 

#     secrets:
#       - qbittorrent_user
#       - qbittorrent_password
# #! The webui is at <your-ip>:8888 and the default username/password is admin/adminadmin

# secrets:
#   qbittorrent_user:
#     file: ./secrets/.qbittorrent_user
#   qbittorrent_password:
#     file: ./secrets/.qbittorrent_password

networks:
  default:
    name: fileshare-network


#   tunnel:
#     container_name: cloudflared-tunnel
#     image: cloudflare/cloudflared
#     restart: unless-stopped
#     command: tunnel run
#     environment:
#       - TUNNEL_TOKEN=mytokengoeshere

# networks:
#   default:
#     external:
#       name: fileshare-network
